Clean up a few stale TODOs
get10101/itchysats pull request #1336
Opened 2022-02-03 09:04 UTC by thomaseizinger

2022-02-03 11:48 UTC, luckysori approved these changes
A much needed culling imo. Thanks!

2022-02-03 23:14 UTC, klochowicz approved these changes
thank you for the cleanup!

2022-02-03 23:21 UTC, klochowicz requested changes, later dismissed

2022-02-03 23:21 UTC, klochowicz commented on daemon/src/model/cfd.rs
> -        }
I'm afraid you need to keep that as the tests are failing. At this stage we're not yet `during_contract_setup` - I have once tried to align this protocol with others and use that flag more, but the PR never got in due to awkwardness of calling it "contract setup proposed". 

The TODO should go away though, as it was actively misleading - sorry for that! 😭 It should say "once it's aligned with other protocols"

2022-02-09 04:29 UTC, thomaseizinger commented
bors r+

2022-02-09 05:15 UTC, thomaseizinger commented
bors r+

2022-02-09 05:29 UTC, merged