Ensure message order at the end of rollover
get10101/itchysats pull request #2200
Opened 2022-06-08 10:25 UTC by da-kami

This should mitigate a problem related to libp2p-rollover, where the taker closed a substream too early.
If both parties send and then wait for the other party in parallel it is unclear who will receive first.
It can happen that the taker sent and received and closed the stream, while the maker is still reading the message that was sent by the taker. This can lead to a panic because the substream is already close.
By ensuring that the taker first sends and then waits to receive, and the maker first waits to receive and then sends should solve this problem.

This is backwards compatible, because old takers will do the same as before (for send then wait to receive).

---

Note: We can decide for changing this for `contract setup` as well, but I have not so far. Once we change it into a libp2p protocol it will have to be changed.

2022-06-09 00:23 UTC, bonomat approved these changes
Why does closing a substream on one side result in a panic on the otherside? This sounds like something we should fix because you can't guarantee that a substream stays open. 

Even though it looks a bit ugly to have this match in here, I think the solution is OK. Next step I'd like to see though is splitting this protocol into two files, one for the maker and for taker. The order of sending and receiving messages does matter in our protocols and that's the only way of how to design it properly.

2022-06-09 00:32 UTC, klochowicz commented
I am not sure whether this is the issue (see comment on the issue)

2022-06-09 00:48 UTC, klochowicz requested changes
I feel like we should stop using `select_next_some()` instead (see the issue). We could gracefully handle this on the new protocol level

2022-06-09 04:37 UTC, da-kami commented
After more analysis of https://github.com/itchysats/itchysats/issues/2199 we came to the conclusion that it is unclear if the `panic` is related to the substream being closed by the other party. 

Likely this problem is related to introduction of the `FailureCounter` that had a severe bug. We are reverting the failure counter here: https://github.com/itchysats/itchysats/pull/2207

I'm changing this PR to draft, will close after further monitoring.

2022-06-13 07:21 UTC, da-kami commented
> Why does closing a substream on one side result in a panic on the otherside? This sounds like something we should fix because you can't guarantee that a substream stays 

It is likely because of using `select_next_some`. We should not do that, see https://github.com/itchysats/itchysats/issues/2199#issuecomment-1153561917

> Even though it looks a bit ugly to have this match in here, I think the solution is OK. Next step I'd like to see though is splitting this protocol into two files, one for the maker and for taker. The order of sending and receiving messages does matter in our protocols and I think that's the only way of how to design it properly.

Yes! I think we cannot just send and receive in parallel - this was never a good design in the first place. It is error prone and I think at least for the last message we have to ensure the message order, so I think this PR is needed. 
I agree that we should properly model the protocol and split it into two files as follow up!

2022-06-13 22:59 UTC, bonomat commented on daemon/src/setup_contract.rs
> +            sink.send(RolloverMsg::Msg3(RolloverMsg3))
Should we consider a sending timeout?

2022-06-13 22:59 UTC, bonomat approved these changes

2022-06-14 05:50 UTC, luckysori approved these changes
I think this patch is harmless and I do like the predictability of knowing who sends what message when, but I don't understand what problem this is fixing. You're saying that we need to actively wait for the other party to finish the protocol before we can drop the substream on our side? That sounds incredibly annoying and brittle.

But I would be keen to see `contract_setup_maker` and `contract_setup_taker` functions, which is where this patch is ultimately taking us.

2022-06-14 08:32 UTC, da-kami commented
> I think this patch is harmless and I do like the predictability of knowing who sends what message when, but I don't understand what problem this is fixing. You're saying that we need to actively wait for the other party to finish the protocol before we can drop the substream on our side? That sounds incredibly annoying and brittle.
> 
> But I would be keen to see `contract_setup_maker` and `contract_setup_taker` functions, which is where this patch is ultimately taking us.

I do see the argument that closing the substream should not lead to message loss.
I have been thinking about this a lot, and I cannot explain 100% why this is happening. 
The behavior I see (i.e. whenever the taker closes the substream the maker runs into a problem where the stream returns `Ready(None)`) lead me to create this fix. The fact that this currently causes a panic is irrelevant. The stream will still report `Ready(None)`, which will cause the maker to exit with an error while the taker succeeded.

Sending is `async`, but when using `send` this should include a `flush`. As far as I understand this should guarantee that the message is sent. But, I don't know what happens if you send, flush and then wait to receive - while the other party is doing exactly the same. Once you are done receiving you close the stream. But how is your sent message guaranteed to arrive at the other side? 

It might be worth creating a test where we try to reproduce this behaviour in isolation to understand better what is happening.

I do believe that this change will fix that problem, because it is clear who is sending and who is receiving. I don't think we have this uncertainty when implementing it this way.

2022-06-14 10:33 UTC, luckysori commented
> > I think this patch is harmless and I do like the predictability of knowing who sends what message when, but I don't understand what problem this is fixing. You're saying that we need to actively wait for the other party to finish the protocol before we can drop the substream on our side? That sounds incredibly annoying and brittle.
> > But I would be keen to see `contract_setup_maker` and `contract_setup_taker` functions, which is where this patch is ultimately taking us.
> 
> I do see the argument that closing the substream should not lead to message loss. I have been thinking about this a lot, and I cannot explain 100% why this is happening. The behavior I see (i.e. whenever the taker closes the substream the maker runs into a problem where the stream returns `Ready(None)`) lead me to create this fix. The fact that this currently causes a panic (due to `select_next_some`) is irrelevant. The stream will still report `Ready(None)`, which will cause the maker to exit with an error while the taker succeeded.
> 
> Sending is `async`, but when using `send` this should include a `flush`. As far as I understand this should guarantee that the message is sent. But, I don't know what happens if you send, flush and then wait to receive - while the other party is doing exactly the same. Once you are done receiving you close the stream. But how is your sent message guaranteed to arrive at the other side?
> 
> It might be worth creating a test where we try to reproduce this behaviour in isolation to understand better what is happening.
> 
> I do believe that this change will fix that problem, because it is clear who is sending and who is receiving. I don't think we have this uncertainty when implementing it this way.

Thanks for the explanation. I completely agree with trying to reproduce the behaviour in a test, because it's not something that I would have expected to happen. But feel free to merge this in the meantime!

2022-06-15 01:59 UTC, da-kami commented
I tried to reproduce this in a test but was unable to. I will see to push something later. It might be related to the test setup and dropping the stream (I am not setting the test up over the wire with two binaries...).

Additionally, I also had another look at the `select_next_some` implementation and I think the problem could be related to the first assert where we run into the panic:

```
impl<St: ?Sized + FusedStream + Unpin> Future for SelectNextSome<'_, St> {
    type Output = St::Item;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        assert!(!self.stream.is_terminated(), "SelectNextSome polled after terminated");

        if let Some(item) = ready!(self.stream.poll_next_unpin(cx)) {
            Poll::Ready(item)
        } else {
            debug_assert!(self.stream.is_terminated());
            cx.waker().wake_by_ref();
            Poll::Pending
        }
    }
}
```

The line `assert!(!self.stream.is_terminated(), "SelectNextSome polled after terminated");` asserts prior to actually checking `ready`. This could be error prone - We would have to evaluate when `is_terminated` would result to true and if it is possible for the stream to still yield `ready!` even if `terminated` is set. I was unable to dig that deep yet.
It would be great to get to the very bottom of this to ensure that the stream behaves as expected and we don't run into problems where one side finishes and the other ones tries to read from the terminated stream.

If this is where the problem comes from then it would be contained to using `select_next_some` and we don't have to ensure the message order.
We can still opt for ensuring message order because, at least to my mind, this is better protocol design than what we currently do.

2022-06-15 07:44 UTC, klochowicz approved these changes

2022-06-15 07:53 UTC, klochowicz commented
bors r+

2022-06-15 08:04 UTC, merged

2022-06-15 10:55 UTC, da-kami commented
Another note:

Unfortunately the problem is not just related to `select_next_some`, we do see `Empty stream` error messages in the logs after merging the `select_next_some` fix:

```
2022-06-15 16:05:28	maker	
{"timestamp":"2022-06-15T06:05:28.527828138Z","level":"WARN","fields":{"message":"Rollover failed: Empty stream instead of Msg3","order_id":"83bd8ef8-86be-4773-98d0-3d72404e488e"},"target":"model::cfd"}
	
2022-06-15 16:05:28	maker	
{"timestamp":"2022-06-15T06:05:28.525060542Z","level":"ERROR","fields":{"message":"Rollover failed: Empty stream instead of Msg3","order_id":"83bd8ef8-86be-4773-98d0-3d72404e488e"},"target":"daemon::rollover::protocol"}
	
2022-06-15 16:05:28	(no unique labels)	
{"timestamp":"2022-06-15T06:05:28.527828138Z","level":"WARN","fields":{"message":"Rollover failed: Empty stream instead of Msg3","order_id":"83bd8ef8-86be-4773-98d0-3d72404e488e"},"target":"model::cfd"}
	
2022-06-15 16:05:28	(no unique labels)	
{"timestamp":"2022-06-15T06:05:28.525060542Z","level":"ERROR","fields":{"message":"Rollover failed: Empty stream instead of Msg3","order_id":"83bd8ef8-86be-4773-98d0-3d72404e488e"},"target":"daemon::rollover::protocol"}
```

Let's hope that merging this PR will fix this for now. I am working on generally changing the rollover protocol to be more deterministic and let the taker always send first and the maker always wait for a message first.