Revert addition of instrumentation argument to cargo aliases
get10101/itchysats pull request #2379
Opened 2022-07-06 17:38 UTC by luckysori

Without an OTEL collector available locally we just emit errors nonstop.

2022-07-06 17:40 UTC, klochowicz requested changes
but we have OTEL collector available locally? It's enough to  run `jaeger.sh`.

if anything, we can hide tonic debug logs, if you don't want to run `jaeger.sh`.

2022-07-06 22:56 UTC, bonomat approved these changes
I'm in favor of this and rather add a second command to run with instrumentation on, e.g. 

```
dev-maker-instrumented = "run --bin maker -- --instrumentation testnet"
...
```

2022-07-07 08:40 UTC, klochowicz commented
> I'm in favor of this and rather add a second command to run with instrumentation on, e.g.
> 
> ```
> dev-maker-instrumented = "run --bin maker -- --instrumentation testnet"
> ...
> ```

I guess this is a reasonable middle ground; I'll add these 2 new aliases as a second commit to this PR.

2022-07-07 09:24 UTC, klochowicz commented
After merging https://github.com/itchysats/itchysats/pull/2381 (which disables all OTEL logs by default), would there any upside of having 2 sets of aliases? I would prefer keeping it enabled as this will be more representative of our production/testnet env.

2022-07-07 09:29 UTC, Restioson commented
Related: maybe `start_all` should start jaeger too, or have an option to do so?

2022-07-07 10:15 UTC, klochowicz commented
> Related: maybe `start_all` should start jaeger too, or have an option to do so?

this would add Docker dependency to it, but  I don't mind it much as it's mostly for dev too.
 Also, but as @bonomat pointed out, a short guide about instrumentation in README might also do the trick!

2022-07-07 11:04 UTC, luckysori commented
With https://github.com/itchysats/itchysats/pull/2381 and letting `start_all.sh` start `jaeger` too I think we don't need to merge this PR anymore.

2022-07-07 11:04 UTC, closed without merging