Remove dependencies from bitmex stream lib
get10101/itchysats pull request #3255
Opened 2022-11-15 14:09 UTC by holzeis

Adding the itchysats bitmex-stream as dependency resulted into the known dependency conflict of the normalization-unicode between url and bip39. I look into the bitmex stream lib and got rid of the url depdendency to make it useable from 10101.

2022-11-15 22:42 UTC, bonomat commented on crates/bitmex-stream/src/lib.rs
> +    fn sign(&self, method: Method, expires: u64, url: &str, body: &str) -> Signature {
Given `url` should now only be the path you could call it `path`.

2022-11-15 23:01 UTC, klochowicz commented
I found a simpler alternative which we might want to consider: https://github.com/itchysats/itchysats/pull/3256 (just relaxing patch version requirements is enough). Tested locally with your project, can push a fixup to your PR if it gets merged.

2022-11-15 23:35 UTC, bonomat commented on crates/bitmex-stream/src/lib.rs
> +            let signature = credentials.sign(Method::GET, expires, &url, "");
Does this still work? Before we passed in a `Url` and called `.path()` on it, returning only the `path` of the url, now you pass in the whole `url`.

2022-11-15 23:38 UTC, bonomat commented on crates/bitmex-stream/src/lib.rs
> +            let signature = credentials.sign(Method::GET, expires, &url, "");
I tested it for you, it does not 😅
```
2022-11-15T23:36:36.300115Z  INFO authenticated_api: {"status":401,"error":"Signature not valid.","meta":{},"request":{"op":"authKeyExpires","args":["**********--oa9",1668555400,"XXXXXXX"]}}
```

2022-11-15 23:38 UTC, bonomat requested changes
This breaks signing unfortunately.

2022-11-16 01:16 UTC, klochowicz commented
I suspect this will not be needed if we go with #3256

2022-11-16 05:21 UTC, holzeis commented on crates/bitmex-stream/src/lib.rs
> +            let signature = credentials.sign(Method::GET, expires, &url, "");
see comment on this commit 8f935e9dfc704b12eb6c98abd873db30dd39aece. I changed the api asking the caller to provide the path + query parameters without the host. The tests are working.

2022-11-16 05:21 UTC, holzeis commented
Closing in favor of #3256

2022-11-16 05:21 UTC, closed without merging

2022-11-16 05:22 UTC, holzeis commented
> I found a simpler alternative which we might want to consider: #3256 (just relaxing patch version requirements is enough). Tested locally with your project, can push a fixup to your PR if it gets merged.

Thanks @klochowicz thats indeed the bettter solution.