Cleanup `unwrap`s throughout the codebase
get10101/itchysats pull request #400
Opened 2021-10-20 07:43 UTC by thomaseizinger

- Make function that never fails non-fallible
- Disallow `.unwrap` in prod code and use expect for remaining ones
- Rewrite matrix_solve to not contain `unwrap`

2021-10-20 10:44 UTC, da-kami commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
Can you maybe walk me through the change tomorrow? I have a hard time validating that the changed code does the same as the original. Are there tests that ensure the same behavior?

2021-10-20 10:48 UTC, da-kami commented on daemon/src/to_sse_event.rs
> +                    margin: cfd.margin().expect("margin to be available"),
nit: The margins are actually calculated, I think a `context(...)?` is more appropriate here. 

Note: We please also remove the TODO above, I don't think we will ever action this.

2021-10-20 11:58 UTC, DeliciousHair commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
@da-kami This is simply a convenience method to solve a matrix equation of the form `AX=B`.

There are no solvers included with `ndarray` (without using BLAS or similar, and thus requiring a fortran compiler) so the pure rust LU solver from `nalgebra` was ninja-ed in that allows us to solve `Ax=b` and then simply iterates over the columns of `X` to determine the columns of `B`.

2021-10-20 21:16 UTC, thomaseizinger commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
> Can you maybe walk me through the change tomorrow?

Not really 😅
I had to `dbg` things myself here as I couldn't visualize it otherwise. But I noticed that we had good test coverage of this code so I just trial-and-errorred until I had something that I think is shorter and easier to read but achieves the same thing.

Ideally, I would have liked a function on `ndarray` to build a matrix from columns. Seems trivial and I don't understand why it doesn't exist ...

There is a lot of unnecessary copying going on here.

2021-10-20 21:20 UTC, thomaseizinger commented on daemon/src/to_sse_event.rs
> +                    margin: cfd.margin().expect("margin to be available"),
The problem is that we are in loop here where we can't return a result.

Needs some more thinking in how we want to handle errors during projection for the UI. 

Should we not display the CFD at all? Just not show margin?

In what cases can we actually fail to calculate the margin?


So many questions ...

2021-10-20 22:53 UTC, da-kami commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
> @da-kami This is simply a convenience method to solve a matrix equation of the form `AX=B`.
> 
> There are no solvers included with `ndarray` (without using BLAS or similar, and thus requiring a fortran compiler) so the pure rust LU solver from `nalgebra` was ninja-ed in that allows us to solve `Ax=b` and this simply iterates over the columns of `X` to determine the columns of `B`.

@DeliciousHair could you verify that the code change does not have any unwanted side effects?

2021-10-20 22:55 UTC, da-kami commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
I'll have a look at the test coverage. I'm afraid of uncovered edge cases that were not effected by the old code but are by the new. Don't wanna be annoying here, just saying it's hard for me to reason about the change :)

2021-10-21 01:00 UTC, DeliciousHair commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
I thought this was well tested already, but it seems to not be the case--maybe I didn't commit the tests or something... Regardless, some minor glitches have been found and tests added to address them. Woot!

2021-10-21 02:18 UTC, thomaseizinger commented
@da-kami Going to rebase this onto master once #406 is merged for more confidence!

2021-10-21 02:51 UTC, DeliciousHair commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
> Ideally, I would have liked a function on `ndarray` to build a matrix from columns. Seems trivial and I don't understand why it doesn't exist ...

I thought [you could do that](https://docs.rs/ndarray/0.15.3/ndarray/struct.ArrayBase.html#method.axis_iter_mut) already? In this case, you'd need to build your output array `X` first as a mutable array of zeros with the correct shape, and then fill the columns in by iterating over `B` with the solver.

I think.

2021-10-21 02:52 UTC, thomaseizinger commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
How do I use this to _build_ a matrix from an iterator of columns?

2021-10-21 04:55 UTC, DeliciousHair commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
Something like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5cc5e1441941aa0bca1e8a145ec56550) perhaps?

2021-10-21 05:28 UTC, DeliciousHair commented on daemon/src/payout_curve/csr_tools.rs
> +        let zeros = Array2::zeros((b_arr.nrows(), 0));
not tested, but the pattern should be:
```rust
    pub fn matrix_solve(&self, b_arr: &Array2<f64>) -> Result<Array2<f64>, Error> {
        let a_arr = self.todense();
        let mut result = Array2::zeros((b_arr.nrows(), b_arr.ncols()));

        for (i, col) in b_arr.axis_iter(Axis(1)).enumerate() {
            let mut slice = result.slice_mut(s![.., i]);
            let update = lu_solve(&a_arr, &col.to_owned());
            slice.assign(&update);
        }

        result
    }
```

2021-10-22 07:36 UTC, thomaseizinger commented
@da-kami @DeliciousHair Rebased and ready to merge at your convenience!

2021-10-22 07:57 UTC, DeliciousHair requested changes

2021-10-22 07:57 UTC, DeliciousHair commented on daemon/src/payout_curve/csr_tools.rs
> +            })?;
Can I suggest this less-verbose version of the above (tested locally against master just now):

```rust
    pub fn matrix_solve(&self, b_arr: &Array2<f64>) -> Result<Array2<f64>, Error> {
        let a_arr = self.todense();
        let mut result = Array2::zeros((b_arr.nrows(), b_arr.ncols()));

        for (i, col) in b_arr.axis_iter(Axis(1)).enumerate() {
            let mut slice = result.slice_mut(s![.., i]);
            let update = lu_solve(&a_arr, &col.to_owned())?;
            slice.assign(&update);
        }

        Ok(result)
    }
```

2021-10-23 06:29 UTC, thomaseizinger commented on daemon/src/payout_curve/csr_tools.rs
> +            })?;
Hmm, not really a fan of the loop, I'd rather have the mutation contained in a `fold` so it is clearer what happens, ie we are building a new matrix from a series of computations.

2021-10-23 21:47 UTC, DeliciousHair commented on daemon/src/payout_curve/csr_tools.rs
> +            })?;
Up to you I guess but I'd argue this is actually less clear, and also runs awry of the conventional pattern suggested.

2021-10-23 22:20 UTC, thomaseizinger commented on daemon/src/payout_curve/csr_tools.rs
> +            })?;
How is it less clear?

I see the following "noise" that I need to think about before I can understand what is happening:

- How does `axis_iter` work?
- What is `Axis(1)`?
- Why do we need `enumerate`?

Having a running index variable to access a part of a data-structure is a code-smell IMO. We are not writing C code here, we have iterators for this :D 

Compared to that, the currently suggestion version makes it clear that we are iterating over all columns, computing something with each column and then building up a matrix again. Ideally, I would have liked to use `collect` for the last part but `ndarray` doesn't support that.

If anything, the 2nd mutable variable in your code can be avoided:

```rust
let update = lu_solve(&a_arr, &col.to_owned())?;
result.slice_mut(s![.., i]).assign(&update);
```

2021-10-24 02:38 UTC, DeliciousHair commented on daemon/src/payout_curve/csr_tools.rs
> +            })?;
Interesting point of view that I had honestly not considered!

By my thinking, the reason I'm claiming my suggestion is "easier" is precisely because of the use of `axis_iter()` and `Axis()`, not as code noise. This suggests a philosophical difference: it is better to use the tools provided by `ndarray` to operate on an `ndarray` object, or is it better to use more bare-bones rust (for lack of a better phrase) in all cases unless absolutely necessary?

Personally, I think the former is generally the better approach (with the condensed step you suggested) as it keeps things clear what sort of "thing" we are working with, rather than defining a "thing" and then just treating it as a generic object. The difference is thus quite subjective and I don't think there is any objective difference* at all.

\* To be sure, I tried writing some benchmarks for the two approaches and the performance difference is consistently within the noise bound of the benchmarking experiments.

2021-10-24 23:18 UTC, da-kami approved these changes
I'm happy with merging this as is and accept changes as suggested by @DeliciousHair in a follow-up.

2021-10-24 23:19 UTC, da-kami commented
@DeliciousHair if the change request is important it would be great if you could take over the PR and add them.

2021-10-24 23:35 UTC, DeliciousHair commented
> @DeliciousHair if the change request is important it would be great if you could take over the PR and add them.

As I mentioned, it makes (essentially) zero performance difference, it's a style issue only--I think I'm right and have thus used the suggested pattern in a number of places, @thomaseizinger thinks he's right and has (presumably) used his pattern elsewhere as well.

In the end, doesn't seem to matter so do feel free to accept.

2021-10-25 06:53 UTC, DeliciousHair approved these changes

2021-10-26 00:18 UTC, da-kami commented
bors r+

2021-10-26 00:28 UTC, merged