Fix price type
get10101/itchysats pull request #405
Opened 2021-10-20 23:10 UTC by DeliciousHair

Replacement of structs with public data to ones with private data

Addresses #357 and #365. Although not a very large change, this PR ends up touching rather a lot of code.

* Converted types `Usd`, `Leverage` and `Percent` to something that is appropriate to this application
* Created new types `Price` and `InversePrice` to use for BTC/USD exchange rate with appropriate algebraic ops implemented as well.
* Added new positive tests
* The function `daemon::model::calculate_profit()` has been changed substantially as the updated types make the existing workflow needlessly complex
* Some tests (mostly in `cfd.rs` required updating) in order to make use of the new types.
* Minor edit to `.gitignore` to avoid accidental pushing of DB to repository--should have been it's own item, added here to fix a problem that arose during this work.

NOTE:
* There may be an excess of algebraic ops implemented, some pruning may be appropriate.

2021-10-21 03:06 UTC, thomaseizinger reviewed
Couple of comments to mull over :)

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        }
Use https://doc.rust-lang.org/std/num/struct.NonZeroU8.html here to avoid this error case.

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        };
Just a style thing but I don't like `else if` blocks. I would change this to:

```suggestion
        if value.to_f64().unwrap().abs() <= f64::EPSILON {
            return Result::Err(Error::ZeroExchangeRate);
        }
        
        if value.to_f64().unwrap() < 0f64 {
            return Result::Err(Error::NegativeExchangeRate);
        };
```

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        if value.to_f64().unwrap().abs() <= f64::EPSILON {
Use https://docs.rs/rust_decimal/1.16.0/rust_decimal/prelude/struct.Decimal.html#method.is_zero instead.

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        } else if value.to_f64().unwrap() < 0f64 {
Use https://docs.rs/rust_decimal/1.16.0/rust_decimal/prelude/struct.Decimal.html#method.is_sign_negative instead.

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        let out = self.value * Decimal::from_u8(rhs.value).unwrap();
For `u8`s, I think you should be able to use `From`: https://docs.rs/rust_decimal/1.16.0/rust_decimal/prelude/struct.Decimal.html#impl-From%3Cu8%3E

And that doesn't panic.

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        self.value.fmt(f)
Formatting should perhaps trim to two decimal places?

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +#[derive(Debug, Copy, Clone, Serialize, Deserialize, PartialEq, PartialOrd)]
Do we really want to derive `Serialize` and `Deserialize` here or should we customize the implementation as we did for `Usd`?

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +// impl From<f64> for Result<Usd> {
There is `TryFrom` is you need a fallible conversion trait.

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +#[derive(Debug, Copy, Clone, Serialize, Deserialize, PartialEq, PartialOrd)]
These derives will conflict with the manually declared ones!

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        let rate = ExchangeRate::new(usd.value).unwrap();
I don't think that is a good practice for the test, better initialize this also with `dec!(123.456)`.

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        assert_eq!(res, Amount::from_sat(100_000_000));
There is a constant for 1 BTC.

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        let res = usd * leverage / leverage;
I would prefer hardcoded expected values over than computed ones.

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +        let usd = Usd::new(dec!(123.456));
Would be great to use test values that are closer to our real world data.

2021-10-21 03:06 UTC, thomaseizinger commented on daemon/src/model.rs
> +    fn algebra_with_exchange_rate() {
This might be more expressive of what is happening here.

```suggestion
    fn usd_for_1_btc_buys_1_btc() {
```

2021-10-21 03:10 UTC, DeliciousHair commented on daemon/src/model.rs
> +        }
As an FYI, I actually started with this type but the problem was that except for this error case, all the other features that it offers in terms of our use-case are still experimental and thus in nightly only. So I went back to `u8` for overall convenience.

Can change though, no bid deal either way.

2021-10-21 06:39 UTC, thomaseizinger commented on daemon/src/model.rs
> +        }
You can use `NonZeroU8` in the fn signature but use a `u8` internally for convenience!

Best of both worlds :)

2021-10-26 01:24 UTC, da-kami requested changes
Great work! This improves understandability a lot!

I have one blocking comment concerning the guard for the `short` `payout` in the `profit` calculation that is based on the `long`'s liquidation price. It might just be a misunderstanding on my side though 😅

Comment on commits: 

Please make sure to clean up the commit history! I think it's good enough to squash the code into one commit. For future work it would be nice to have some clean commits with distinct work, so we can review by commit. 
e.g. for the `.gitignore` file change it would have been great to have a separate commit and a commit message that explains why this change was done in one sentence.

2021-10-26 01:24 UTC, da-kami commented on daemon/src/db.rs
> +        price: row.initial_price.parse::<Price>()?,
❓I'm surprised these type hints are actually needed - can rust not infer the type here based on what is returned?

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model.rs
> +    #[error("Exchange rate of zero is not allowed.")]
```suggestion
    #[error("Price of zero is not allowed.")]
```

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model.rs
> +    #[error("Negative exchange rate is unimplemented.")]
```suggestion
    #[error("Negative price is unimplemented.")]
```

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model.rs
> +        Amount::from_str_in(&btc.to_string(), Denomination::Bitcoin).unwrap()
Just to check my understanding of the motivation for `InversePrice`: 
Was `InversePrice` introduced, so we can keep these calculation impls separate from the `Price`? Is there any other motivation for using `InversePrice` over `Price`?

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model.rs
> +// TODO: leaving Percent as-is for this PR as the plan is to
Please remove this Todo and create an issue for it instead. We should definitely not talk about specific PRs in Todos in the code - once the PR is merged there is no context for this Todo...

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model.rs
> +        let liquidation_price = price * leverage / (leverage + 1);
🛠 This test does not test any code at the moment - besides constructing types. If that is intended please rename the test to reflect that.

I think the test should test the actual code where we calculate the liquidation price, not calculate the liquidation price in the test!

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model/cfd.rs
> +    let test = closing_price <= long_liquidation_price;
```suggestion
    let is_not_liquidation = closing_price <= long_liquidation_price;
```

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model/cfd.rs
> +            //     a = xi * Ll / (Ll + 1)
🛠 Hard to understand what `a` and `b` represent - can we somehow come up with better names?

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model/cfd.rs
> +            //     a = xi * Ll / (Ll + 1)
🛠 Hard to understand what `a` and `b` represent - can we somehow come up with better names?

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model/cfd.rs
> +                    quantity / (initial_price * leverage)
I could validate that the payout is calculated with the same formula as before.

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model/cfd.rs
> +            let payout = match test {
❓❗️ Here we are using the long liquidation price (the `test` variable) when defining the bounds for the `Sell` (= `short`) position. Is that correct? 
The liquidation price for the `short` position is substantially higher than the one for `long`. I think the liquidation price calculation has to distinguish between `long` and `short`! Also, the liquidation price for `short` must be guarded by `>= closing_price`.

Or am I misunderstanding something?

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model/cfd.rs
> +            let payout = match test {
I don't think we should calculate the liquidation price separately in here, but use the liquidation price calculation that already exists (and is hopefully tested for sanity)!

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model/cfd.rs
> +        let price = Price::new(dec!(46125)).unwrap();
I validated that these values correspond to our GSheet based model. 
For future reference, it would have been great to have a commit, that changes the maintenance margin to `0` prior to removing it - that way you can showcase that the calculation is the same (i.e. tests pass with maintenance margin `0` and without maintenance margin based on the same input and expect).

2021-10-26 01:24 UTC, da-kami commented on daemon/src/model/cfd.rs
> +            dec!(15.99999899200001).into(),
I think it is sane, but I have a hard time validating that change 😅

2021-10-26 01:27 UTC, DeliciousHair commented on daemon/src/model.rs
> +        Amount::from_str_in(&btc.to_string(), Denomination::Bitcoin).unwrap()
Nope, none. It's just a safe + convenient way of doing `1/price` is all, since the guardrails are on `Price::new()`

2021-10-26 01:28 UTC, DeliciousHair commented on daemon/src/model.rs
> +    #[error("Negative exchange rate is unimplemented.")]
oops!

2021-10-26 01:32 UTC, DeliciousHair commented on daemon/src/db.rs
> +        price: row.initial_price.parse::<Price>()?,
Hm, you may be correct... Lemme check that I didn't make extra work here.

EDIT:
Nope, this is "correct" in this context as we are parsing the data to `Decimal` type which is not something we can handle out-of-the-box just yet (see [this issue](https://github.com/launchbadge/sqlx/issues/1489) in particular). This is not to say it cannot be improved, only that this is where we are for the moment.

2021-10-26 01:36 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> +            let payout = match test {
> Or am I misunderstanding something?

I think you may be; can we please discuss this at some point?

2021-10-26 01:40 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> +            //     a = xi * Ll / (Ll + 1)
I'm going to say not really, as in this case I'm trying to show what the algebra does, as opposed to how the "concept" works. In this context, using variables `a` and `b` I think make good sense as it removes the context completely, which is the objective in the comment.

2021-10-26 01:42 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> +                    quantity / (initial_price * leverage)
Sorry, I'm not sure what you're saying here?

2021-10-26 01:44 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> +            dec!(15.99999899200001).into(),
Yeah, I couldn't figure out where the first number was coming from either; suspect there was actually a logic error that was being allowed in via the test, but I really don't know TBH.

2021-10-26 01:45 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> +        let price = Price::new(dec!(46125)).unwrap();
Fair enough, but this further ties back to detail that the `maintenance_margin` has now been stripped out completely until it has been properly defined.

2021-10-26 02:30 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> +            let payout = match test {
> I don't think we should calculate the liquidation price separately in here, but use the liquidation price calculation that already exists (and is hopefully tested for sanity)!

The existing function is:
```rust
fn calculate_liquidation_price(leverage: Leverage, price: Price) -> Price {
    price * leverage / (leverage + 1)
}
```
which I wanted to remove TBH as having such trivial calculations relegated out to distinct functions makes the code harder to read IMHO as I the maintainer have to navigate around to discover that a function that does something akin to `a + b` has been used at some location rather than just writing `a + b`.

If the math was more complicated, sure! But in this case, I really think it is just making things less clear.

Happy enough to go either way, but will make consistent.

Also, re: testing please note from `model.rs` that:
```rust
#[test]
fn test_liquidation() {
    let usd = Usd::new(dec!(61234.5678));
    let leverage = Leverage::new(5).unwrap();
    let price = Price::new(dec!(61234.5678)).unwrap();
    let expected_buyin = Amount::from_str_in("0.2", Denomination::Bitcoin).unwrap();

    let liquidation_price = price * leverage / (leverage + 1);
    let inv_price = InversePrice::new(price);
    let inv_liquidation_price = InversePrice::new(liquidation_price);

    let long_buyin = usd / (price * leverage);
    let long_payout =
        (usd / leverage) * ((leverage + 1) * inv_price - leverage * inv_liquidation_price);

    assert_eq!(long_buyin, expected_buyin);
    assert_eq!(long_payout, Amount::ZERO);
}
```

2021-10-26 03:26 UTC, klochowicz reviewed
it's getting close, I guess the commits should be squashed with some nice description before it can get merged.

2021-10-26 03:26 UTC, klochowicz commented on .gitignore
>  /*.sqlite*
```suggestion
```

2021-10-26 03:26 UTC, klochowicz commented on .gitignore
>  /*.sqlite*
nit: I believe you don't need this one, if we're ignoring all the sqlite databases in the repo with your new change

2021-10-26 03:26 UTC, klochowicz commented on daemon/src/model.rs
> +        Self(Decimal::ONE / value.0)
could we please add a check that `value.0` is not `ZERO`? (I know that currently price can't be created with zero, but it could be a footgun if we relax that requirement or perform calculations resulting in zero.

2021-10-26 03:26 UTC, klochowicz commented on daemon/src/model.rs
> +// rahther than having a distinct struct for it.
Perhaps we could create a ticket instead of TODO? (I think we agreed on that during last retro)

2021-10-26 03:26 UTC, klochowicz commented on daemon/src/model/cfd.rs
> +
Please remove the empty lines here as it interferes with `rustfmt` (@thomaseizinger always points it out in my reviews 😄 )

(here and below)

2021-10-26 03:26 UTC, klochowicz commented on daemon/src/model/cfd.rs
> -    maintenance_margin_rate: &Decimal,
what happened to `maintenance_margin_rate`? It seems odd that it was removed as part of this PR. If you'd like to remove it, I'd prefer to open up a separate PR so we can focus and discuss it, instead of blocking the refactor

2021-10-26 03:29 UTC, DeliciousHair commented on daemon/src/model.rs
> +        let liquidation_price = price * leverage / (leverage + 1);
Sorry, but I disagree. The types are in fact being tested in the sense that we are creating some values and doing some algebra. The fact that the algebra is testing that the liquidation price yields a payout of zero is merely a convenient test value.

And again, computing the liquidation price is trivial--the function in another module is the exact same one-line operation.

As for renaming the test, alright.

2021-10-26 03:36 UTC, da-kami commented on daemon/src/model/cfd.rs
> +                    quantity / (initial_price * leverage)
I am always comparing what we have in code with the model that we have in Google sheets. That way I can somehow verify that we have the expected outcome (besides the tests). I just added those comments so that other reviewers might see that it was verified against the GSheet model. that what @bonomat and me did with previous PRs that changed calculations.

2021-10-26 03:38 UTC, DeliciousHair commented on daemon/src/model.rs
> +        Self(Decimal::ONE / value.0)
Since `Price.0 = ZERO` is blocked, I don't  see what you're getting at here as the check would serve no purpose.

2021-10-26 04:09 UTC, klochowicz commented on daemon/src/model.rs
> +        Self(Decimal::ONE / value.0)
I mentioned above -e - if anyone ever decides to support price being `0` or be able to calculate it (as a result of some computation, not via `new()`), then this will be an error waiting to happen.
It's much easier to be explicit here, instead of forcing a reader to put trust that these types will be set in lockstep. 

Is there any harm in being a bit more explicit here stating the contract?

2021-10-26 07:50 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> +            //     a = xi * Ll / (Ll + 1)
Given that this is a comment only and is written up as formulae, I think the use of the single-letter values is appropriate within the context.

2021-10-26 07:51 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> +                    quantity / (initial_price * leverage)
Ah, gotcha!

2021-10-26 07:52 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> +            let payout = match test {
Fixed with current update, should all be well now!

2021-10-26 07:54 UTC, DeliciousHair commented on daemon/src/model/cfd.rs
> -    maintenance_margin_rate: &Decimal,
It was simply dropped as it was ad-hoc'd into things as the pedagogy of said item relied on some cumbersome algebra. With the current structure it is easy to compute on the fly in both the payout curve and the profit calculation(s), or can be stuck onto, say, the `Cfd` struct as a static value--doesn't really matter TBH; note that the resulting functions in `cfd.rs` are simply:

```rust
pub fn calculate_buy_margin(price: Price, quantity: Usd, leverage: Leverage) -> Amount {
    quantity / (price * leverage)
}

fn calculate_sell_margin(price: Price, quantity: Usd) -> Amount {
    quantity / price
}

fn calculate_liquidation_price(leverage: Leverage, price: Price) -> Price {
    price * leverage / (leverage + 1)
}
```

2021-10-26 08:10 UTC, DeliciousHair commented on daemon/src/model.rs
> +        Self(Decimal::ONE / value.0)
I suppose not, so added it is!

2021-10-26 09:16 UTC, da-kami approved these changes
nice, thanks!

2021-10-26 09:16 UTC, da-kami commented on daemon/src/model.rs
> +// rahther than having a distinct struct for it.
It's still a Todo, can we move to a ticket?

2021-10-26 09:16 UTC, da-kami commented on daemon/src/model.rs
> +    fn test_liquidation_as_expected() {
```suggestion
    fn test_algebra() {
```

Reasoning: This test is not about testing the liquidation price but just algebra and constructing types. The liquidation price is just used as an example, but no code calculating the liquidation price is tested.

2021-10-26 21:51 UTC, DeliciousHair commented on daemon/src/model.rs
> +    fn test_liquidation_as_expected() {
That is actually (more or less) what I had and was told to change it to (more or less) the name that is there.  I'll change it again as I prefer your suggestion, but perhaps we should create a style-guide for this sort of thing as there is clearly some inconsistency happening?

2021-10-26 22:56 UTC, klochowicz commented on daemon/src/model/cfd.rs
> -    maintenance_margin_rate: &Decimal,
This explanation makes sense, thank you! Would you mind mentioning it also in the commit message? otherwise people might be wondering why it went away during a refactor.

2021-10-26 22:57 UTC, klochowicz approved these changes

2021-10-27 00:04 UTC, da-kami commented
bors r+

2021-10-27 00:11 UTC, merged