Ensure we always know about Order::Term * announcements
get10101/itchysats pull request #419
Opened 2021-10-22 05:40 UTC by bonomat

When looking into https://github.com/comit-network/hermes/issues/360 I realized we forgot to trigger `FetchAnnouncement` when receiving a roll-over request. 
This is fixed with this PR.

I found this a bit cumbersome to have to do this manually. Instead, we should sync regularly and ensure we have attestations for the next 24h. 

This is also related to the discussion @da-kami and @thomaseizinger had in https://github.com/comit-network/hermes/issues/349

2021-10-22 07:32 UTC, thomaseizinger requested changes
Thanks!

I think there is a simpler design where we merge the two sync messages.

2021-10-22 07:32 UTC, thomaseizinger commented on daemon/src/oracle.rs
> -pub struct FetchAnnouncement(pub BitMexPriceEventId);
With the removal of this, we don't actually need to sync every 5 seconds but can increase that interval.

This was only 5 seconds because we wanted to "quickly" react to incoming messages of `FetchAnnouncement`. That was sort of a hack anyway from the beginning so I am happy that it is going away!

2021-10-22 07:32 UTC, thomaseizinger commented on daemon/src/oracle.rs
> +    fn ensure_having_announcements(&mut self, term: Duration) {
Once we increase the interval, I think we can merge this with sync to simplify the interface of this actor.

2021-10-22 07:32 UTC, thomaseizinger commented on daemon/src/oracle.rs
> +pub struct FetchAnnouncements(pub Duration);
With https://github.com/comit-network/hermes/pull/412, the term will be configurable. Should we just make the term an argument to the `oracle::Actor`? Fits the constructor better than the message IMO, esp. given that this message is going away if we merge it with `Sync`.

2021-10-22 07:32 UTC, thomaseizinger commented on daemon/src/oracle.rs
> +            }
If this gets merged with `sync`, I think the entire state of `pending_announcements` can go away because you can just directly use `spawn_fallible` in here to spawn away the fetching.

2021-10-22 07:32 UTC, thomaseizinger commented on daemon/src/taker.rs
> +        );
For simplicity, we can have the taker sync announcements as well, otherwise we will need two different APIs for talking to the oracle actor.

It is not strictly necessary though so we might want to keep that in mind if it ever causes problems.

2021-10-22 22:12 UTC, bonomat commented on daemon/src/taker.rs
> +pub const TERM: time::Duration = time::Duration::hours(24);
The changes in here are not ideal because of the what was introduced in #412. 

As mentioned in https://github.com/comit-network/hermes/pull/412#issuecomment-949986797 
a CFD does not have a term. This is an implementation detail and it should actually not be tempered with besides for test purposes. Hence, I reintroduce a constant for this.

2021-10-24 04:08 UTC, thomaseizinger approved these changes
Nice, thank you!

Much in favor of this implementation. More resilient and smaller API surface too!

2021-10-24 04:08 UTC, thomaseizinger commented on daemon/src/oracle.rs
> +        self.ensure_having_announcements(self.term, ctx);
Passing `self.term` is odd for a fn that is called on `self`.

2021-10-24 04:08 UTC, thomaseizinger commented on daemon/src/taker.rs
> +pub const TERM: time::Duration = time::Duration::hours(24);
Perhaps we should just call this `ANNOUNCEMENT_LOOKAHEAD` or something. At least on the taker side, this variable has nothing to do with the "term".

2021-10-24 04:08 UTC, thomaseizinger commented on daemon/src/oracle.rs
>              announcements: HashMap::new(),
I think we should actually save those to the DB. Seems unnecessary to fetch them on every startup of the app.

2021-10-25 04:43 UTC, da-kami commented on daemon/src/taker.rs
> +pub const TERM: time::Duration = time::Duration::hours(24);
> a CFD does not have a term

I think this is a terminology problem. Even in a traditional cfd you have to define the start and end price that the cfd is bound to. So, there is no term in the sense of closing the cfd, but there can be recurring fees that are bound to time periods, such as daily interest. 
What we call "term" just tries to put the time period between start price and end price into code. I am happy to rename it - could not come up with a better word than "term". I am not sure `ANNOUNCEMENT_LOOKAHEAD` makes this clearer. What do you think @DeliciousHair ?

2021-10-25 04:47 UTC, DeliciousHair commented on daemon/src/taker.rs
> +pub const TERM: time::Duration = time::Duration::hours(24);
I think `ANNOUNCEMENT_LOOKAHEAD` or perhaps `ANNOUNCEMENT_TIME_INTERVAL` are improvements, yes. I'm adding the second suggestion as it makes it very clear that this is a temporal value.

2021-10-25 04:58 UTC, da-kami commented on daemon/src/oracle.rs
>              announcements: HashMap::new(),
I think saving in db should be done in a follow up.

2021-10-25 05:28 UTC, klochowicz commented on daemon/src/oracle.rs
>              announcements: HashMap::new(),
shall I create a ticket to track it, so it won't get lost?

2021-10-25 06:03 UTC, da-kami approved these changes
I don't see any blockers, currently rebasing this work and will see to get it merged once done!

I created a follow-up PR for renaming `term`:

https://github.com/comit-network/hermes/pull/424

2021-10-25 06:13 UTC, da-kami commented on daemon/src/oracle.rs
>              announcements: HashMap::new(),
yeah, please create one!

2021-10-26 01:28 UTC, da-kami commented
I think it is fair to assume that #426 is unrelated to the code changes in this PR. Keeping #426 for further investigation and merging this PR now.

2021-10-26 02:57 UTC, da-kami commented
bors r+

2021-10-26 02:59 UTC, klochowicz commented on daemon/src/oracle.rs
>              announcements: HashMap::new(),
#430

2021-10-26 03:04 UTC, merged