Only change Cfd state when we succeed to contact Taker
get10101/itchysats pull request #441
Opened 2021-10-27 07:24 UTC by klochowicz

The situation outlined and fix #440 was repeated a few times in the code, there
were a few other places that preemptively changed the Cfd state before
taker was successfully contacted.

2021-10-27 23:34 UTC, da-kami requested changes

2021-10-27 23:34 UTC, da-kami commented on daemon/src/maker_cfd.rs
> +        let txid = self
❗️ We only retry to send the transaction if we transition to `PendingOpen`, otherwise the whole `Cfd` will be transitioned to `SetupFailed` upon restart at the moment!

So, if sending the transaction fails, we won't transition to `PendingOpen` and will never retry to send upon restart.
This could lead to a similar behaviour as described here: https://github.com/comit-network/hermes/issues/364

2021-10-27 23:34 UTC, da-kami commented on daemon/src/maker_cfd.rs
> +        let dlc = cfd.open_dlc().context("CFD was in wrong state")?;
This change does not make a whole lot of difference; both statements can fail but don't change any state.
What was the motivation for changing this?

2021-10-27 23:34 UTC, da-kami commented on daemon/src/taker_cfd.rs
> +        let txid = self
❗️same problem as described above.

2021-10-27 23:36 UTC, da-kami commented on daemon/src/maker_cfd.rs
> +        let txid = self
Note: #364 describes how we can tackle this during failure in contract setup itself; the overall idea is to be mindful about what the other party knows, because we cannot ensure the other party won't publish if we ran into an error. 
For #440 this is irrelevant because it is prior to contract setup, i.e. no signatures (...) exchanged yet :)

2021-10-27 23:39 UTC, da-kami commented
Would be cool if we could cover these changes with failing tests. This goes towards writing tests that include the restart behavior - I think we can easily achieve that, but will need some more time until we have them. 
Simulating that sending the transaction failed should be possible. This, however, is already very high test coverage level. Let's see to reach that :)

2021-10-28 02:00 UTC, closed without merging

2021-10-28 02:01 UTC, klochowicz commented
> Would be cool if we could cover these changes with failing tests. This goes towards writing tests that include the restart behavior - I think we can easily achieve that, but will need some more time until we have them. Simulating that sending the transaction failed should be possible. This, however, is already very high test coverage level. Let's see to reach that :)

great idea 🏆

2021-10-28 02:06 UTC, klochowicz commented on daemon/src/maker_cfd.rs
> +        let txid = self
Thanks for the explanation - I have indeed missed the whole point that this particular cfd state is there for the purpose of handling this problem!

Armed with the new knowledge, I've closed the PR as it made no sense anymore :)
🐣